name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }} 

    - name: Build docker image
      run: docker build -t ghcr.io/${{ secrets.GH_USER }}/jorney.api:${{ steps.generate_sha.outputs.sha }} .

    - name: Push image
      run: |
        docker push ghcr.io/${{ secrets.GH_USER }}/jorney.api:${{ steps.generate_sha.outputs.sha }}
        docker tag ghcr.io/${{ secrets.GH_USER }}/jorney.api:${{ steps.generate_sha.outputs.sha }} ghcr.io/${{ secrets.GH_USER }}/jorney.api:latest
        docker push ghcr.io/${{ secrets.GH_USER }}/jorney.api:latest