name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
      
    - name: Run tests
      run: go test

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }} 
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/maria-eduarda90/jorney.api:${{ steps.generate_sha.outputs.sha }}
          ghcr.io/maria-eduarda90/jorney.api:latest

    # - name: Build docker image
    #   run: docker build -t ghcr.io/maria-eduarda90/jorney.api:${{ steps.generate_sha.outputs.sha }} .

    # - name: Tag docker image as latest
    #   run: docker tag ghcr.io/maria-eduarda90/jorney.api:${{ steps.generate_sha.outputs.sha }} ghcr.io/maria-eduarda90/jorney.api:latest

    # - name: Push image
    #   run: |
    #     docker push ghcr.io/maria-eduarda90/jorney.api:${{ steps.generate_sha.outputs.sha }}
    #     docker push ghcr.io/maria-eduarda90/jorney.api:latest